"""Helpers shared by the golden producers: hashing, normalization, patching, figure capture.

The goldens pin *outputs* (file bytes, numbers, figure JSON), never APIs. When a phase of
the refactor moves code, only `producers.py` changes to call the new API; the stored
expectations under `expected/` stay untouched unless a change is deliberate.
"""

import contextlib
import hashlib
import json
import re
import shutil
import tempfile
from html.parser import HTMLParser
from pathlib import Path
from unittest import mock

GOLDEN_DIR = Path(__file__).resolve().parent
FIXTURES = GOLDEN_DIR / "fixtures"
EXPECTED = GOLDEN_DIR / "expected"
DUMPS = GOLDEN_DIR / "_dumps"

# Scenario version label used for every set generated by the producers.
VERSION = "vG"

# Scenario ids used to embed the version ("vG-normal-optimization-001"). The refactor
# drops it (D12), so both sides are compared with the prefix removed.
_ID_PREFIX = re.compile(rf"(?<![A-Za-z0-9]){VERSION}-(low|normal|high)-")


def normalize_ids(text: str) -> str:
    return _ID_PREFIX.sub(r"\1-", text)


def sha_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha_text(text: str) -> str:
    return sha_bytes(text.encode())


def sha_json(value) -> str:
    return sha_text(json.dumps(value, sort_keys=True, separators=(",", ":"), default=str))


def tree_digest(root: Path, pattern: str = "scenario_*.json") -> dict[str, str]:
    """`{relative path: sha}` of every matching file, ids normalized in names and bytes."""
    return {
        normalize_ids(str(path.relative_to(root))): sha_text(normalize_ids(path.read_text()))
        for path in sorted(root.rglob(pattern))
    }


@contextlib.contextmanager
def patched(targets: dict):
    """Patch several `module.attr` targets at once."""
    with contextlib.ExitStack() as stack:
        for target, value in targets.items():
            stack.enter_context(mock.patch(target, value))
        yield


@contextlib.contextmanager
def figure_capture():
    """Record the JSON digest of every Plotly figure rendered to HTML, in call order."""
    import plotly.io as pio

    original = pio.to_html
    digests: list[str] = []

    def recording(fig, *args, **kwargs):
        digests.append(sha_text(pio.to_json(fig, validate=False, engine="json")))
        return original(fig, *args, **kwargs)

    with mock.patch("plotly.io.to_html", recording):
        yield digests


class _VisibleText(HTMLParser):
    def __init__(self):
        super().__init__()
        self.parts: list[str] = []
        self._skip = 0

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "style"):
            self._skip += 1

    def handle_endtag(self, tag):
        if tag in ("script", "style") and self._skip:
            self._skip -= 1

    def handle_data(self, data):
        if not self._skip and data.strip():
            self.parts.append(" ".join(data.split()))


def visible_text(html: str) -> str:
    parser = _VisibleText()
    parser.feed(html)
    return "\n".join(parser.parts)


def dump(name: str, content: str) -> None:
    """Full, human-diffable copy of an output (gitignored), for investigating a mismatch."""
    DUMPS.mkdir(parents=True, exist_ok=True)
    (DUMPS / name).write_text(content)


class Workspace:
    """Temporary directories shared by the producers of one session.

    Some goldens consume another's output (the CA reads the generated sets, the reports
    read them too), so prerequisites are produced once and cached here.
    """

    def __init__(self):
        self.root = Path(tempfile.mkdtemp(prefix="golden-"))
        self.cache: dict = {}

    def path(self, *parts: str) -> Path:
        path = self.root.joinpath(*parts)
        path.mkdir(parents=True, exist_ok=True)
        return path

    def once(self, key: str, build):
        if key not in self.cache:
            self.cache[key] = build()
        return self.cache[key]

    def close(self) -> None:
        shutil.rmtree(self.root, ignore_errors=True)

    def relativize(self, text: str) -> str:
        return text.replace(str(self.root), "<WS>").replace(str(FIXTURES), "<FIX>")
